name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/project.clj') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Install dependencies
      run: lein deps
    - name: Check format
      run: lein cljfmt check
    - name: Run kibit
      run: lein kibit
    - name: Run eastwood
      run: lein eastwood
    - name: Run tests
      run: lein test
